# Generated by Django 5.1 on 2024-09-06 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='car',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
