# Generated by Django 5.1 on 2024-09-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0002_car_date_car_latitude_car_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_description', models.CharField(max_length=100)),
                ('name_on_card', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry_year', models.CharField(max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
