# Generated by Django 5.1 on 2024-09-10 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0004_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_range', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='address',
        ),
        migrations.RemoveField(
            model_name='car',
            name='date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='car',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='car',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='car',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='binary.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binary.car')),
                ('mileage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binary.carmileage')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binary.carmodel')),
            ],
        ),
    ]
