# Generated by Django 5.1 on 2024-09-10 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0005_carmileage_remove_car_address_remove_car_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='mileage',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='car',
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='car_model',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='car',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='car',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='car',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='car',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='CarMileage',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
