# Generated by Django 5.1 on 2024-09-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0006_alter_cardetails_mileage_remove_carmodel_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
