# Generated by Django 5.1 on 2024-09-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0007_alter_car_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='speed',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
