# Generated by Django 5.1 on 2024-10-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0010_coverageselection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverageselection',
            old_name='selected_at',
            new_name='date_selected',
        ),
        migrations.AlterField(
            model_name='coverageselection',
            name='coverage_type',
            field=models.CharField(choices=[('Basic', 'Basic (Liability)'), ('Standard', 'Standard (Liability + Collision)'), ('Premium', 'Premium (Full Coverage)')], max_length=20),
        ),
    ]
