# Generated by Django 5.1 on 2024-10-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0012_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
