# Generated by Django 5.1 on 2024-10-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0013_claim_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='approved',
        ),
    ]
