# Generated by Django 5.1 on 2024-10-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0014_remove_claim_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardetails',
            old_name='car',
            new_name='car_name',
        ),
    ]
