# Generated by Django 5.1 on 2024-10-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0015_rename_car_cardetails_car_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('Comprehensive Claims', 'Comprehensive Claims'), ('Collision Claims', 'Collision Claims'), ('Liability Claims', 'Liability Claims'), ('Personal Injury Protection (PIP) Claims', 'Personal Injury Protection (PIP) Claims'), ('Glass And Windshield Claims', 'Glass And Windshield Claims')], max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('preferred_contact_method', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone')], max_length=15)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
