# Generated by Django 4.2.7 on 2024-10-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0016_claimsubmit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='preferred_contact_method',
        ),
    ]
