# Generated by Django 4.2.7 on 2024-10-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0017_remove_claim_preferred_contact_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=50)),
                ('date_submitted', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=10)),
            ],
        ),
    ]
