# Generated by Django 4.2.7 on 2024-10-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0019_notificationpy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivers_license', models.FileField(upload_to='documents/')),
                ('Proof_Of_ID', models.FileField(upload_to='documents/')),
                ('vehicle', models.FileField(upload_to='documents/')),
                ('roadworthy', models.FileField(upload_to='documents/')),
                ('income', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
